Actions summaries
TeachBooks/deploy-book-workflow pull request #5
Opened 2024-04-17 15:21 UTC by severinbratus

Resolves #1

2024-04-18 03:49 UTC, rlanzafame commented
Looks good to me, I am excited to use it! (but don't have time at the moment - I'll let Tom sign off on this one :))

2024-04-18 06:27 UTC, Tom-van-Woudenberg requested changes
Awesome!

I've changed one thing (double / somewhere) and tried implementing something else (but failed): can you give the full link in the aliases table? So https://teachbooks.github.io/.../alias --> https://teachbooks.github.io/.../target instead of only alias --> target

And maybe show the branches deployed table only when the process is finished? Otherwise it might give the impression that the urls are already available, even if it finishes at a later stage.

2024-04-19 15:31 UTC, severinbratus commented
> Awesome!
> 
> I've changed one thing (double / somewhere) and tried implementing something else (but failed): can you give the full link in the aliases table? So https://teachbooks.github.io/.../alias --> https://teachbooks.github.io/.../target instead of only alias --> target
> 
> And maybe show the branches deployed table only when the process is finished? Otherwise it might give the impression that the urls are already available, even if it finishes at a later stage.

Fixed both in new commit, please see is this summary looks OK: https://github.com/TeachBooks/testable-template/actions/runs/8723981979

2024-04-19 15:33 UTC, Tom-van-Woudenberg approved these changes

2024-04-19 15:33 UTC, merged